import 'codemirror/mode/javascript/javascript.js';
import 'codemirror/mode/shell/shell.js';
import 'codemirror/mode/handlebars/handlebars.js';
import 'codemirror/mode/htmlmixed/htmlmixed.js';
import 'codemirror/mode/xml/xml.js';
import 'codemirror/mode/css/css.js';
import "codemirror/mode/asn.1/asn.1.js";
import "codemirror/mode/clojure/clojure.js";
import 'codemirror/addon/edit/closebrackets.js';
import 'codemirror/addon/edit/closetag.js';
import 'codemirror/mode/ebnf/ebnf.js';
import 'codemirror/addon/edit/matchbrackets.js';
import 'codemirror/keymap/vim.js';
import "codemirror/addon/search/search.js";
import "codemirror/addon/search/searchcursor.js";
import "codemirror/addon/search/jump-to-line.js";
import "codemirror/addon/dialog/dialog.js";
import "codemirror/addon/comment/comment.js";
import "codemirror/addon/comment/continuecomment.js";
import "codemirror/addon/display/panel.js";
import "./hints/sema-show-hint.js"
// import "codemirror/addon/dialog/dialog.css";
// import 'codemirror/theme/idea.css';
// import "codemirror/theme/monokai.css";
// import "codemirror/theme/icecoder.css";
// import "codemirror/theme/shadowfox.css";
// import 'codemirror/theme/oceanic-next.css';
// import 'codemirror/lib/codemirror.css';
// import './icecoder.css';
// import './monokai.css';
// import './shadowfox.css';

